# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pkgui < Formula
  desc "terminal dashboard for everything you've installed"
  homepage "https://github.com/bhavya-dang/pkgui"
  version "0.1.2"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bhavya-dang/pkgui/releases/download/v0.1.2/pkgui_0.1.2_darwin_amd64.tar.gz"
      sha256 "4d73523487ce49da51a147b170510045b107ea87f7a3700ef4e9fa89d0a84ea7"

      define_method(:install) do
        bin.install "pkgui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bhavya-dang/pkgui/releases/download/v0.1.2/pkgui_0.1.2_darwin_arm64.tar.gz"
      sha256 "2c52d21dd535dfc8702d58fd79ddfb31a9ad83c59445a0d60d27cdfa253e1067"

      define_method(:install) do
        bin.install "pkgui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bhavya-dang/pkgui/releases/download/v0.1.2/pkgui_0.1.2_linux_amd64.tar.gz"
      sha256 "8bf229d6a5a06629dece17108948176203b0e93466891904b75d4fd5cb013a1d"
      define_method(:install) do
        bin.install "pkgui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bhavya-dang/pkgui/releases/download/v0.1.2/pkgui_0.1.2_linux_arm64.tar.gz"
      sha256 "83aece036ae473aa684ce350d1c3ccdd73b623455e1518ef05177ce93332eeb4"
      define_method(:install) do
        bin.install "pkgui"
      end
    end
  end
end
